### ISSUE TITLE
GRBL CONTROLLER 0.8.4 DOES NOT WORK ON WINDOWS 7 ULTIMATE SP1

### ISSUE THREAD

**Issue by emvert** [jarekkt/smallsmt-openpnp#2]
I have purchased a cnc machine from china and using xloader, I flashed grbl 0.9.

I am now trying to use it on my Windows 7 ultimate SP 1 but the grblControl 0.8.4 will immediately freeze right after you opened it."stopped working".  I tried updating .net framework 3.5 but still it is not working. I appreciate any help from you guys please?

**Comment by jarekkt** [comment]
This project is not grbl related
